name: "Lighthouse Badger"

########################################################################
# DEFINE YOUR INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# INPUTS as Secrets (env) for not manually triggered workflows
env:
  URLS: 'https://jawad-robolearn.github.io'
  REPO_BRANCH: 'Jawad-RoboLearn/jawad-robolearn.github.io master'
  MOBILE_LIGHTHOUSE_PARAMS: '--only-categories=performance,accessibility,best-practices,seo --throttling.cpuSlowdownMultiplier=2 --max-wait-for-load=10000'
  DESKTOP_LIGHTHOUSE_PARAMS: '--only-categories=performance,accessibility,best-practices,seo --preset=desktop --throttling.cpuSlowdownMultiplier=1 --max-wait-for-load=10000'

# TRIGGERS
on:
  page_build:
  # Uncomment to enable scheduled runs
  # schedule:
  #   - cron: '55 23 * * 0' # e.g. every Sunday at 23:55
  workflow_dispatch:

########################################################################
# THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master  # Use the correct branch if it’s different

      - name: Checkout Lighthouse Badges Repository
        uses: actions/checkout@v4
        with:
          repository: "myactionway/lighthouse-badges"
          path: temp_lighthouse_badges_nested

      - name: Generate Lighthouse Badges
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ env.URLS }}
          mobile_lighthouse_params: ${{ env.MOBILE_LIGHTHOUSE_PARAMS }}
          desktop_lighthouse_params: ${{ env.DESKTOP_LIGHTHOUSE_PARAMS }}
          token: ${{ secrets.LIGHTHOUSE_BADGER_TOKEN }}  # Ensure this token is set correctly